name: Publish NPM packages

on:
  push:
    branches:
      - "main"
    paths:
      - "fabr-bind-cli/package.json"

concurrency:
  group: "publish-npm"
  cancel-in-progress: true

jobs:
  public-fabr-bind-cli:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fabr-bind-cli

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Run Tests
        run: npm run test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: fabr-bind-cli/package.json
          access: public

  